name: Deploy Streamlit Application


on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EchoSecretTest
        run: |
          echo $WELLNESSGURU
        env:
          WELLNESSGURU: ${{ secrets.WELLNESSGURU }}

      
        
        
          

      
        

      
      
