name: Deploy Streamlit Application


on:
  repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SecretTestStreamlitRun
        run: |
          export WELLNESSGURU="${{ secrets.WELLNESSGURU }}"
          streamlit run accesstoken.py
        env:
          WELLNESSGURU: ${{ secrets.WELLNESSGURU }}

      
        
        
          

      
        

      
      
